call mvn install:install-file -Dfile=axiom-api-1.2.14.jar -DgroupId=org.apache.ws-commons.axiom -DartifactId=axiom-api -Dversion=1.2.14 -Dpackaging=jar
call mvn install:install-file -Dfile=axiom-impl-1.2.14.jar -DgroupId=org.apache.ws-commons.axiom -DartifactId=axiom-impl -Dversion=1.2.14 -Dpackaging=jar
call mvn install:install-file -Dfile=axis2-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2 -Dversion=1.6.2 -Dpackaging=jar
call mvn install:install-file -Dfile=axis2-transport-http-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-transport-http -Dversion=1.6.2 -Dpackaging=jar
call mvn install:install-file -Dfile=axis2-transport-local-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-transport-local -Dversion=1.6.2 -Dpackaging=jar
call mvn install:install-file -Dfile=auditor-2.0.0.jar -DgroupId=org.openhealthtools.ihe.atna -DartifactId=auditor -Dversion=2.0.0 -Dpackaging=jar
call mvn install:install-file -Dfile=braid-base-1.2.2.jar -DgroupId=com.misys.braid -DartifactId=braid-base -Dversion=1.2.2 -Dpackaging=jar
call mvn install:install-file -Dfile=cda-1.0.0.201109121753.jar -DgroupId=org.openhealthtools.mdht.uml -DartifactId=cda -Dversion=1.0.0.201109121753 -Dpackaging=jar
call mvn install:install-file -Dfile=common-2.6.0.v20100914-1218.jar -DgroupId=org.eclipse.emf -DartifactId=common -Dversion=2.6.0.v20100914-1218 -Dpackaging=jar
call mvn install:install-file -Dfile=commons-lang-2.6.jar -DgroupId=commons-lang -DartifactId=commons-lang -Dversion=2.6 -Dpackaging=jar
call mvn install:install-file -Dfile=commons-codec-1.8.jar -DgroupId=commons-codec -DartifactId=commons-codec -Dversion=1.8 -Dpackaging=jar
call mvn install:install-file -Dfile=context-2.0.0.jar -DgroupId=org.openhealthtools.ihe.atna -DartifactId=context -Dversion=2.0.0 -Dpackaging=jar
call mvn install:install-file -Dfile=ebXML._2._1-2.0.0.jar -DgroupId=org.openhealthtools.ihe.common -DartifactId=ebXML._2._1 -Dversion=2.0.0 -Dpackaging=jar
call mvn install:install-file -Dfile=ebXML._3._0-2.0.0.jar -DgroupId=org.openhealthtools.ihe.common -DartifactId=ebXML._3._0 -Dversion=2.0.0 -Dpackaging=jar
call mvn install:install-file -Dfile=ecore-2.6.1-v20100914-1218.jar -DgroupId=org.eclipse.emf -DartifactId=ecore -Dversion=2.6.1-v20100914-1218 -Dpackaging=jar
call mvn install:install-file -Dfile=ecore-3.0.2.R30x_v201101110610.jar -DgroupId=org.eclipse.ocl -DartifactId=ecore -Dversion=3.0.2.R30x_v201101110610 -Dpackaging=jar
call mvn install:install-file -Dfile=ecore.xml-2.5.0.v20100521-1846.jar -DgroupId=org.eclipse.emf -DartifactId=ecore.xml -Dversion=2.5.0.v20100521-1846 -Dpackaging=jar
call mvn install:install-file -Dfile=hl7.datatypes-1.0.0.201109121753.jar -DgroupId=org.openhealthtools.mdht.uml -DartifactId=hl7.datatypes -Dversion=1.0.0.201109121753 -Dpackaging=jar
call mvn install:install-file -Dfile=hl7.rim-1.0.0.201109121753.jar -DgroupId=org.openhealthtools.mdht.uml -DartifactId=hl7.rim -Dversion=1.0.0.201109121753 -Dpackaging=jar
call mvn install:install-file -Dfile=hl7.vocab-1.0.0.201109121753.jar -DgroupId=org.openhealthtools.mdht.uml -DartifactId=hl7.vocab -Dversion=1.0.0.201109121753 -Dpackaging=jar
call mvn install:install-file -Dfile=hl7v2-2.0.0.jar -DgroupId=org.openhealthtools.ihe.common -DartifactId=hl7v2 -Dversion=2.0.0 -Dpackaging=jar
call mvn install:install-file -Dfile=java-2.0.17-v201004271640.jar -DgroupId=lpg.runtime -DartifactId=java -Dversion=2.0.17-v201004271640 -Dpackaging=jar
call mvn install:install-file -Dfile=log4j-1.2.16.jar -DgroupId=log4j -DartifactId=log4j -Dversion=1.2.16 -Dpackaging=jar
call mvn install:install-file -Dfile=metadata-2.0.0.jar -DgroupId=org.openhealthtools.ihe.xds -DartifactId=metadata -Dversion=2.0.0 -Dpackaging=jar
call mvn install:install-file -Dfile=metadata.extract-2.0.0.jar -DgroupId=org.openhealthtools.ihe.xds -DartifactId=metadata.extract -Dversion=2.0.0 -Dpackaging=jar
call mvn install:install-file -Dfile=metadata.extract.cdar2-2.0.0.jar -DgroupId=org.openhealthtools.ihe.xds -DartifactId=metadata.extract.cdar2 -Dversion=2.0.0 -Dpackaging=jar
call mvn install:install-file -Dfile=metadata.transform-2.0.0.jar -DgroupId=org.openhealthtools.ihe.xds -DartifactId=metadata.transform -Dversion=2.0.0 -Dpackaging=jar
call mvn install:install-file -Dfile=neethi-3.0.2.jar -DgroupId=org.apache.neethi -DartifactId=neethi -Dversion=3.0.2 -Dpackaging=jar
call mvn install:install-file -Dfile=nodeauth-2.0.0.jar -DgroupId=org.openhealthtools.ihe.atna -DartifactId=nodeauth -Dversion=2.0.0 -Dpackaging=jar
call mvn install:install-file -Dfile=ocl-3.0.2.R30x_v201101110610.jar -DgroupId=org.eclipse.ocl -DartifactId=ocl -Dversion=3.0.2.R30x_v201101110610 -Dpackaging=jar
call mvn install:install-file -Dfile=openpixpdq-1.1.jar -DgroupId=org.openhealthexchange.openpixpdq -DartifactId=openpixpdq -Dversion=1.1 -Dpackaging=jar
call mvn install:install-file -Dfile=soap-2.0.0.jar -DgroupId=org.openhealthtools.ihe.xds -DartifactId=soap -Dversion=2.0.0 -Dpackaging=jar
call mvn install:install-file -Dfile=source-2.0.0.jar -DgroupId=org.openhealthtools.ihe.xds -DartifactId=source -Dversion=2.0.0 -Dpackaging=jar
call mvn install:install-file -Dfile=utils-2.0.0.jar -DgroupId=org.openhealthtools.ihe -DartifactId=utils -Dversion=2.0.0 -Dpackaging=jar
call mvn install:install-file -Dfile=ws.axis2-2.0.0.jar -DgroupId=org.openhealthtools.ihe.common -DartifactId=ws.axis2 -Dversion=2.0.0 -Dpackaging=jar
call mvn install:install-file -Dfile=xds-2.0.0.jar -DgroupId=org.openhealthtools.ihe.xds -DartifactId=xds -Dversion=2.0.0 -Dpackaging=jar
call mvn install:install-file -Dfile=consumer-2.0.0.jar -DgroupId=org.openhealthtools.ihe.xds -DartifactId=consumer -Dversion=2.0.0 -Dpackaging=jar
call mvn install:install-file -Dfile=openpixpdqaudit-1.jar -DgroupId=openpixpdq -DartifactId=openpixpdqaudit -Dversion=1 -Dpackaging=jar
call mvn install:install-file -Dfile=braid-base-1.2.jar -DgroupId=braid -DartifactId=braid-base -Dversion=1.2 -Dpackaging=jar
call mvn install:install-file -Dfile=jxl-2.6.12.jar -DgroupId=net.sourceforge.jexcelapi -DartifactId=jxl -Dversion=2.6.2 -Dpackaging=jar
call mvn install:install-file -Dfile=antlr-2.7.7.jar -DgroupId=antlr -DartifactId=antlr -Dversion=2.7.7 -Dpackaging=jar
call mvn install:install-file -Dfile=aopalliance-1.0.jar -DgroupId=aopalliance -DartifactId=aopalliance -Dversion=1.0 -Dpackaging=jar
call mvn install:install-file -Dfile=org.openhealthtools.ihe.common.mllp_2.0.0.jar -DgroupId=org.openhealthtools.ihe.common -DartifactId=mllp -Dversion=2.0.0 -Dpackaging=jar
call mvn install:install-file -Dfile=org.openhealthtools.ihe.pix.source_2.0.0.jar -DgroupId=org.openhealthtools.ihe.pix -DartifactId=source -Dversion=2.0.0 -Dpackaging=jar
call mvn install:install-file -Dfile=hl7v2-core-0.2.0.200812311053.jar -DgroupId=org.eclipse.ohf -DartifactId=hl7v2-core -Dversion=0.2.0.200812311053 -Dpackaging=jar